dataset:
  dataloader_n_jobs: 8
  image_margin_size: 0
  mean:
  - 0.485
  - 0.456
  - 0.406
  name: cityscapes
  only_19_from_cityscapes: true
  scales:
  - 0.5
  - 1.5
  std:
  - 0.229
  - 0.224
  - 0.225
  train_key: train
  window_size:
  - 513
  - 513
model:
  add_on_layers_type: deeplab_simple
  base_architecture: deeplabv2_resnet101
  num_classes: 19
  pretrained: true
  prototype_activation_function: log
  prototype_shape:
  - 190
  - 64
  - 1
  - 1
paths:
  data_dir: /project/hnguyen2/mvu9/datasets/cityscapes
  model_dir: ./models
  results_dir: ./results
system:
  gpus: 1
  load_coco: false
  random_seed: 20220227
  start_checkpoint: ''
training:
  early_stopping_patience: 100
  finetune_steps: 10000
  ignore_void_class: true
  iter_size: 5
  joint_batch_size: 2
  joint_lr_add_on_layers: 0.00025
  joint_lr_features: 2.5e-05
  joint_lr_prototype_vectors: 0.00025
  joint_steps: 150000
  joint_weight_decay: 0.0005
  last_layer_lr: 1.0e-05
  loss_weight_cross_entropy: 1.0
  loss_weight_kld: 0.25
  loss_weight_l1: 0.0001
  poly_lr_power: 0.9
  warmup_batch_size: 2
  warmup_lr_add_on_layers: 0.00025
  warmup_lr_prototype_vectors: 0.00025
  warmup_steps: 15000
  warmup_weight_decay: 0.0005
